import type { Project } from "./types";

/*
 * Recent Commissions — real photographs.
 * GENERATED by scripts/gen-2026-photos.mjs from "Updated Website Photos 7.27.26".
 * 33 photographs. Re-run the script to regenerate.
 */
export const commissions: Project = {
  title: "Recent Commissions",
  slug: "commissions",
  blocks: [
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-01.jpg",
        width: 1920,
        height: 1371,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-02.jpg",
        width: 1200,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-03.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-04.jpg",
        width: 1536,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-05.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-06.jpg",
        width: 1372,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-07.jpg",
        width: 1281,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-08.jpg",
        width: 1600,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-09.jpg",
        width: 1600,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-10.jpg",
        width: 1440,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-11.jpg",
        width: 1920,
        height: 1248,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-12.jpg",
        width: 1078,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-13.jpg",
        width: 8117,
        height: 11364,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-14.jpg",
        width: 1920,
        height: 1536,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-15.jpg",
        width: 1270,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-16.jpg",
        width: 1372,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-17.jpg",
        width: 1536,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-18.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-19.jpg",
        width: 1920,
        height: 1281,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-20.jpg",
        width: 1600,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-21.jpg",
        width: 1536,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-22.jpg",
        width: 1302,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-23.jpg",
        width: 1500,
        height: 2101,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-24.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-25.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-26.jpg",
        width: 1415,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-27.jpg",
        width: 1500,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-28.jpg",
        width: 1372,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-29.jpg",
        width: 1600,
        height: 1143,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-30.jpg",
        width: 1357,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-31.jpg",
        width: 1372,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-32.jpg",
        width: 1536,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/inside/inside-33.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
  ],
};
