import type { Project } from "./types";

/*
 * Recent Commissions — real photographs from theatraff.com.
 *
 * GENERATED by scripts/gen-photos.mjs from the theatraff.com archive.
 * 69 photographs. Re-run the script to regenerate.
 */
export const commissions: Project = {
  title: "Recent Commissions",
  slug: "commissions",
  blocks: [
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/469a5268-cop2y-copy.jpg",
        width: 1379,
        height: 2000,
        alt: "President Joe Biden in the Oval Office, photographed by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/maryweb.jpg",
        width: 1072,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/polley-traff-05-final-copy.jpg",
        width: 2000,
        height: 2500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-01.jpg",
        width: 1000,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/climate-cover.jpg",
        width: 816,
        height: 1000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-janietaylor-04-final.jpg",
        width: 1706,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-wyjudd-finals-014-copy.jpg",
        width: 1334,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-001.jpg",
        width: 1071,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "wide-landscape",
      image: {
        src: "/images/archive/weisz-traff.jpg",
        width: 2000,
        height: 1300,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-daddario-02.jpg",
        width: 1792,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-chastain-final-02-copy.jpg",
        width: 1747,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-06.jpg",
        width: 1071,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-ng-lp-final-19.jpg",
        width: 1631,
        height: 2039,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-chastain-final-03-copy.jpg",
        width: 1361,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-fleming-highres-12.jpg",
        width: 1706,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-011.jpg",
        width: 1071,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-janietaylor-27-final.jpg",
        width: 1768,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-stones-001-copy.jpg",
        width: 947,
        height: 1200,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-wyjudd-finals-019-copy.jpg",
        width: 1334,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-weisz-lores-20-copy.jpg",
        width: 1400,
        height: 1960,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-wyjudd-finals-017-copy.jpg",
        width: 1491,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-egan-03-copy-2.jpg",
        width: 2048,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-05.jpg",
        width: 1071,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-3.jpg",
        width: 1600,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1q7a5880-copy-2.jpg",
        width: 2095,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-03.jpg",
        width: 1071,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-1.jpg",
        width: 1600,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-fleming-highres-05.jpg",
        width: 1707,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-wyjudd-030-copy.jpg",
        width: 1371,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-ohara-highres-18.jpg",
        width: 1706,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "wide-landscape",
      image: {
        src: "/images/archive/1q7a0406-copy-2.jpg",
        width: 2560,
        height: 1721,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-weisz-lores-08-new.jpg",
        width: 2048,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-010.jpg",
        width: 1072,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-ohara-highres-07-copy.jpg",
        width: 1883,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "wide-landscape",
      image: {
        src: "/images/archive/ig-02.jpg",
        width: 2100,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-egan-final-02-copy-2.jpg",
        width: 1600,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/coppola-traff-45.jpg",
        width: 997,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/portfolio-56-copy.jpg",
        width: 960,
        height: 1200,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1q7a0014-copy-4.jpg",
        width: 1469,
        height: 2119,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-003.jpg",
        width: 1071,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-chastain-final-16-copy.jpg",
        width: 1382,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-wyjudd-finals-029-copy.jpg",
        width: 1707,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-ohara-highres-17.jpg",
        width: 1706,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "wide-landscape",
      image: {
        src: "/images/archive/traff-weisz-lores-40-new.jpg",
        width: 2000,
        height: 1334,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-janietaylor-01-final.jpg",
        width: 1706,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-fleishmanstars-01.jpg",
        width: 1706,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "wide-landscape",
      image: {
        src: "/images/archive/traff-wyjudd-finals-028-copy.jpg",
        width: 2000,
        height: 1334,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-egan-final-03-copy-2.jpg",
        width: 1359,
        height: 1995,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/q506-nyt-mag-thea-traff-rachel-weisz-03-29-20232353-fnl-copy-tt2-copy-2.jpg",
        width: 1600,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-chastain-final-05-copy.jpg",
        width: 1410,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-chastain-final-01.jpg",
        width: 1736,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-fleishmanstars-02.jpg",
        width: 1874,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/q506-nyt-mag-thea-traff-rachel-weisz-03-29-20232416-fnl-copy-tt2-copy-2.jpg",
        width: 1600,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1q7a5893-copy.jpg",
        width: 2048,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-stones-039-copy.jpg",
        width: 1137,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-04.jpg",
        width: 1072,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-daddario-01.jpg",
        width: 1742,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-daddario-06.jpg",
        width: 1982,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc00646-copy-3.jpg",
        width: 1745,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-stones-019-copy.jpg",
        width: 866,
        height: 1200,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-egan-final-01-copy.jpg",
        width: 1584,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1q7a0117-final-copy.jpg",
        width: 2048,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1q7a6388-copy.jpg",
        width: 2048,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-wyjudd-finals-018-copy.jpg",
        width: 1334,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-stones-016-copy.jpg",
        width: 960,
        height: 1200,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-janietaylor-02-final.jpg",
        width: 1706,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/ig-007.jpg",
        width: 1071,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "wide-landscape",
      image: {
        src: "/images/archive/traff-ng-lp-final-02.jpg",
        width: 2560,
        height: 1797,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-janietaylor-04-final-2.jpg",
        width: 1200,
        height: 1800,
        alt: "Photograph by Thea Traff",
      },
    },
  ],
};
