import type { Project } from "./types";

/*
 * Dance — real photographs.
 * GENERATED by scripts/gen-2026-photos.mjs from "Updated Website Photos 7.27.26".
 * 12 photographs. Re-run the script to regenerate.
 */
export const dance: Project = {
  title: "Dance",
  slug: "dance",
  blocks: [
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-01.jpg",
        width: 1355,
        height: 1897,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-02.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-03.jpg",
        width: 1267,
        height: 1900,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-04.jpg",
        width: 1920,
        height: 1371,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-05.jpg",
        width: 1920,
        height: 1372,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-06.jpg",
        width: 1920,
        height: 1371,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-07.jpg",
        width: 1920,
        height: 1371,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-08.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-09.jpg",
        width: 1372,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-10.jpg",
        width: 1469,
        height: 2057,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-11.jpg",
        width: 1920,
        height: 1371,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/dance/dance-12.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
  ],
};
