import type { Project } from "./types";

/*
 * Elevator Series — real photographs.
 * GENERATED by scripts/gen-2026-photos.mjs from "Updated Website Photos 7.27.26".
 * 8 photographs. Re-run the script to regenerate.
 */
export const elevator: Project = {
  title: "Elevator Series",
  slug: "elevator-series",
  blocks: [
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/elevator/elevator-01.jpg",
        width: 1178,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/elevator/elevator-02.jpg",
        width: 1178,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/elevator/elevator-03.jpg",
        width: 1179,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/elevator/elevator-04.jpg",
        width: 1178,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/elevator/elevator-05.jpg",
        width: 1178,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/elevator/elevator-06.jpg",
        width: 1179,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/elevator/elevator-07.jpg",
        width: 1179,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/elevator/elevator-08.jpg",
        width: 1179,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
  ],
};
