import type { Project } from "./types";

/*
 * Elevator Series — real photographs from theatraff.com.
 *
 * GENERATED by scripts/gen-photos.mjs from the theatraff.com archive.
 * 9 photographs. Re-run the script to regenerate.
 */
export const elevator: Project = {
  title: "Elevator Series",
  slug: "elevator-series",
  blocks: [
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-11.jpg",
        width: 1920,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/tt-004.jpg",
        width: 2048,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-10.jpg",
        width: 2046,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/tt-006.jpg",
        width: 2042,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-12.jpg",
        width: 1922,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/tt-005.jpg",
        width: 2189,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/tt-010-copy-2.jpg",
        width: 2011,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/tt-009-copy-3.jpg",
        width: 2011,
        height: 2560,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-11-2.jpg",
        width: 1200,
        height: 1600,
        alt: "Photograph by Thea Traff",
      },
    },
  ],
};
