import type { HomeCell } from "./types";

/**
 * Home grid — real photographs from the theatraff.com home page.
 * GENERATED by scripts/gen-photos.mjs.
 */
export const homeCells: HomeCell[] = [
  {
    image: {
      src: "/images/archive/q506-nyt-mag-thea-traff-rachel-weisz-03-29-20232353-fnl-copy-tt2-copy.jpg",
      width: 1600,
      height: 2000,
      alt: "Photograph by Thea Traff",
    },
  },
  {
    image: {
      src: "/images/archive/traff-janietaylor-27-final-2.jpg",
      width: 1600,
      height: 2000,
      alt: "Photograph by Thea Traff",
    },
  },
  {
    image: {
      src: "/images/archive/traff-09.jpg",
      width: 1600,
      height: 2000,
      alt: "Photograph by Thea Traff",
    },
  },
  {
    image: {
      src: "/images/archive/traff-final-01-copy.jpg",
      width: 2048,
      height: 2560,
      alt: "Photograph by Thea Traff",
    },
  },
  {
    image: {
      src: "/images/archive/q506-nyt-mag-thea-traff-rachel-weisz-03-29-20232416-fnl-copy-tt2-copy.jpg",
      width: 1600,
      height: 2000,
      alt: "Photograph by Thea Traff",
    },
  },
  {
    image: {
      src: "/images/archive/traff-weisz-lores-49-copy.jpg",
      width: 1600,
      height: 2000,
      alt: "Photograph by Thea Traff",
    },
  },
  {
    image: {
      src: "/images/archive/gladstone-traff-21-copy.jpg",
      width: 1600,
      height: 2000,
      alt: "Photograph by Thea Traff",
    },
  },
  {
    image: {
      src: "/images/archive/finalc-dsc-0884-copy-2.jpg",
      width: 2048,
      height: 2560,
      alt: "Photograph by Thea Traff",
    },
  },
];
