import type { HomeCell } from "./types";

/*
 * Home / landing page — single hero photograph (LP).
 * GENERATED by scripts/gen-2026-photos.mjs from "Updated Website Photos 7.27.26".
 */
export const homeCells: HomeCell[] = [
  {
    image: {
      src: "/images/2026/lp.jpg",
      width: 2000,
      height: 2667,
      alt: "Photograph by Thea Traff",
    },
  },
];
