import type { Project } from "./types";

/*
 * Personal Work (Overview) — real photographs from theatraff.com.
 *
 * GENERATED by scripts/gen-photos.mjs from the theatraff.com archive.
 * 31 photographs. Re-run the script to regenerate.
 */
export const personal: Project = {
  title: "Personal Work",
  slug: "personal",
  blocks: [
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1-dsc02756-2.jpg",
        width: 3349,
        height: 4187,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1q7a1370-copy.jpg",
        width: 2400,
        height: 3600,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1-dsc00950.jpg",
        width: 2285,
        height: 2857,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1-dsc01907.jpg",
        width: 3857,
        height: 4822,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/thea-traff-15.jpg",
        width: 2800,
        height: 3500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/eimg-4154-copy.jpg",
        width: 3456,
        height: 5184,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/new-website-dsc-0478-copy-2.jpg",
        width: 2877,
        height: 4229,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/img-7434.jpg",
        width: 3309,
        height: 4247,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/rina-249-recovered-copy.jpg",
        width: 2402,
        height: 3002,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/40627b50-8052-46cb-a01a-8039cc00cb54-copy.jpg",
        width: 3000,
        height: 3750,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc-0475-2.jpg",
        width: 1838,
        height: 2298,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/kees-final-copy.jpg",
        width: 1788,
        height: 2448,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc00075-copy-2.jpg",
        width: 3925,
        height: 5305,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/thea-traff-02.jpg",
        width: 2759,
        height: 3448,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc09370-copy-2ignew.jpg",
        width: 3916,
        height: 4895,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc08386-copy-2.jpg",
        width: 3395,
        height: 4244,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/vpc-1-copy.jpg",
        width: 3000,
        height: 3750,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc01341-recovered-final.jpg",
        width: 4000,
        height: 5000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/vpc-3-copy.jpg",
        width: 1926,
        height: 2407,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc08008-copy.jpg",
        width: 2587,
        height: 3234,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc04906-recovered-copy.jpg",
        width: 2063,
        height: 2578,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/img-1933-copy-copy.jpg",
        width: 3337,
        height: 4171,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc-0535-copy.jpg",
        width: 2999,
        height: 4229,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/dsc-0101-recovered-copy.jpg",
        width: 1638,
        height: 2048,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/thea-traff-11.jpg",
        width: 2883,
        height: 3604,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1q7a3175-copy2.jpg",
        width: 3125,
        height: 3906,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1-dsc06993-copy-2-copyfinal.jpg",
        width: 3751,
        height: 4689,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/54d6f8bb-b9d7-426d-9ba6-71ab2fcaf16a.jpg",
        width: 640,
        height: 758,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/img-1878-copy.jpg",
        width: 3331,
        height: 4164,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/traff-19.jpg",
        width: 3276,
        height: 4096,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/archive/1-dsc02756-2-2.jpg",
        width: 1200,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
  ],
};
