import type { Project } from "./types";

/*
 * Personal Work — real photographs.
 * GENERATED by scripts/gen-2026-photos.mjs from "Updated Website Photos 7.27.26".
 * 22 photographs. Re-run the script to regenerate.
 */
export const personal: Project = {
  title: "Personal Work",
  slug: "personal",
  blocks: [
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-01.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-02.jpg",
        width: 1440,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-03.jpg",
        width: 1281,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-04.jpg",
        width: 1600,
        height: 2000,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-05.jpg",
        width: 1662,
        height: 2327,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-06.jpg",
        width: 1536,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-07.jpg",
        width: 1372,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-08.jpg",
        width: 1481,
        height: 1777,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-09.jpg",
        width: 1280,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-10.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-11.jpg",
        width: 1372,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-12.jpg",
        width: 1920,
        height: 1371,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-13.jpg",
        width: 1071,
        height: 1500,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-14.jpg",
        width: 1920,
        height: 1371,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-15.jpg",
        width: 1329,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-16.jpg",
        width: 1440,
        height: 1798,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-17.jpg",
        width: 1536,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-18.jpg",
        width: 1936,
        height: 1357,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-19.jpg",
        width: 1372,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-20.jpg",
        width: 1371,
        height: 1920,
        alt: "Photograph by Thea Traff",
      },
    },
    {
      variant: "centered-portrait",
      image: {
        src: "/images/2026/outside/outside-21.jpg",
        width: 1500,
        height: 1875,
        alt: "Photograph by Thea Traff",
      },
    },
  ],
};
